---

- name: create {{ name }} project for {{ user }}
  k8s:
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ name }}"

- name: Add admin role binding for {{ user }} in their project
  k8s:
    state: present
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: admin
        namespace: "{{ name }}"
      subjects:
        - kind: User
          apiGroup: rbac.authorization.k8s.io
          name: "{{ user }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin

#- name: add scc and roles in project {{ name }} for user {{ user }}
#  shell: |
#    oc adm policy add-role-to-user admin {{ user }} -n {{ name }}
