---
# Create knative-serving, knative-eventing projects
- name: create knative projects
  k8s:
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ item }}"
  loop:
    - "openshift-serverless"
    - "knative-serving"
    - "knative-eventing"

# Setup OpenShift Serverless via operator
- name: Create OpenShift Objects for serverless
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/serverless_subscription.yaml

# wait for serverless CRDs
- name: Wait for knative-serving CRD
  k8s_info:
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: knativeservings.operator.knative.dev
  register: r_knserving_crd
  retries: 40
  delay: 10
  until: r_knserving_crd.resources | list | length == 1
  ignore_errors: true

- name: wait for serving project to exist
  k8s_info:
    kind: Project
    api_version: project.openshift.io/v1
    name: "knative-serving"
  register: r_serving_proj
  retries: 40
  delay: 10
  until: r_serving_proj.resources | list | length == 1
  ignore_errors: true

- name: create knative serving CR
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/knative_serving_cr.yaml
  ignore_errors: true

- name: Wait for knative-eventing project to exist
  k8s_info:
    api_version: project.openshift.io/v1
    kind: Project
    name: "knative-eventing"
  register: r_kneventing_project
  retries: 40
  delay: 10
  until: r_kneventing_project.resources | list | length == 1
  ignore_errors: true

- name: create knative eventing CR
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/knative_eventing_cr.yaml
  ignore_errors: true
