---
# Implement your Post Workload deployment tasks here
- name: output workshop info
  debug:
    msg:
    - "user.info: "
    - "user.info: Machine Learning Trac for {{ num_users }} user(s)"

- name: output workshop info guides
  debug:
    msg:
    - "user.info: "
    - "user.info: URL for attendees to get a username assigned to them and links to labs:"
    - "user.info: "
    - "user.info: https://get-a-username-labs-infra.{{ route_subdomain }}"
    - "user.info: "
    - "user.info: You should share this URL (or a shortlink for it) -- It is all they will need to get started!"
    - "user.info: "
    - "user.info: [Instructor Only] To access the admin see which user is assigned to which user ID, use the following:"
    - "user.info: "
    - "user.info: [Instructor Only] https://get-a-username-labs-infra.{{ route_subdomain }}/admin"
    - "user.info: "
    - "user.info: [Instructor Only] Admin login with 'admin' / '{{ workshop_openshift_user_password }}'"

- name: output workshop info guides
  debug:
    msg:
    - "user.info: http://guides-machinelearning-labs-infra.{{ route_subdomain }}"

- name: output workshop info guides
  debug:
    msg:
    - "user.info: "
    - "user.info: OpenShift credentials for attendees: {{ workshop_openshift_user_name }} / {{ workshop_openshift_user_password }}"
    - "user.info: "
    - "user.info: OpenShift Console: {{ console_url }}"
    - "user.info: Cluster admin login with '{{ ocp_username }}' / 'r3dh4t1!'"
  when: not silent|bool

# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload Tasks completed successfully."
  when: not silent|bool
