---
# Implement your Workload deployment tasks here

- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

- name: Setting up num_users for workshop
  debug:
    msg: "Setting up num_users for workshop num_users = {{ num_users }}"

- name: Give access to opentlc-mgr
  shell: |
         oc adm policy add-cluster-role-to-user cluster-admin {{ ocp_username }}

- name: create labs-infra project
  k8s:
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "labs-infra"
        annotations:
          openshift.io/description: ""
          openshift.io/display-name: "Lab Infrastructure"

- name: create notebooks user projects
  include_tasks: create_project.yaml
  vars:
    name: "{{ item[0] }}-notebooks"
    user: "{{ item[0] }}"
  loop: "{{ users|product(['notebooks'])|list }}"

# Setup OpenShift Serverless via operator
- name: Look for serverless subscription
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: serverless-operator
    namespace: openshift-operators
  register: r_serverless_sub

- name: show existing serverless sub
  debug:
    msg: "existing serverless sub: {{ r_serverless_sub }}"

- name: Create OpenShift Objects for Serverless (knative)
  when: r_serverless_sub.resources | list | length == 0
  include_tasks: install-serverless.yaml

# Setup AMQ via operator
- name: Look for amq subscription
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: amq-streams
    namespace: openshift-operators
  register: r_amq_sub

- name: show existing amq sub
  debug:
    msg: "existing amq sub: {{ r_amq_sub }}"

- name: Create OpenShift Objects for Kafka (amq streams)
  when: r_amq_sub.resources | list | length == 0
  include_tasks: install-amqstreams.yaml

- name: Look for Open Data Hub subscription
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: opendatahub-operator
    namespace: openshift-operators
  register: r_odh_sub

- name: show existing Open Data Hub subscription
  debug:
    msg: "existing ODH sub: {{ r_odh_sub }}"
  
# Install Open Data Hub 
- name: Install Open Data Hub
  include_tasks: install-odh.yml

- name: install guides
  include_tasks: install-guides.yaml

- name: install username distribution
  include_tasks: install-username-distribution.yaml

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
