---
become_override: no
ocp_username: opentlc-mgr
silent: False

num_users: 15
module_type: m1

deploy_ceph_cluster: true
deploy_opendatahub: true
deploy_demo: false

guides_url: "https://raw.githubusercontent.com/Red-Hat-SE-RTO/machine-learning-workshop-guides/main"

workshop_openshift_user_name: userXX
workshop_openshift_user_password: 'openshift'

demo_ml_project_namespace: demo-ml
demo_ml_wait_for_service_build: true
demo_ml_run_new_builds_if_already_built: false